-- 코드를 입력하세요
SELECT  MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH
FROM    MEMBER_PROFILE
WHERE   TLNO is NOT NULL
        AND GENDER = 'W'
        AND DATE_OF_BIRTH LIKE '____-03-__'
ORDER BY    MEMBER_ID;